<?php

namespace Database\Seeders\Catalogs;

use App\Enums\EconomicSectorLevel;
use App\Models\Catalogs\EconomicSector;
use Illuminate\Database\Seeder;

class EconomicSectorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // === ISIC: Secciones (nivel 1), Divisiones (nivel 2) y Grupos (nivel 3) ===
        // Nota: los códigos (A, 01, 011, etc.) se usan SOLO para mapear jerarquía; no se guardan (tu tabla no trae "code").

        $sections = [
            ['code' => 'A', 'name' => 'Agricultura, silvicultura y pesca'],
            ['code' => 'B', 'name' => 'Explotación de minas y canteras'],
            ['code' => 'C', 'name' => 'Industrias manufactureras'],
            ['code' => 'D', 'name' => 'Suministro de electricidad, gas, vapor y aire acondicionado'],
            ['code' => 'E', 'name' => 'Suministro de agua; evacuación de aguas residuales, gestión de desechos y descontaminación'],
            ['code' => 'F', 'name' => 'Construcción'],
            ['code' => 'G', 'name' => 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas'],
            ['code' => 'H', 'name' => 'Transporte y almacenamiento'],
            ['code' => 'I', 'name' => 'Actividades de alojamiento y de servicio de comidas'],
            ['code' => 'J', 'name' => 'Información y comunicaciones'],
            ['code' => 'K', 'name' => 'Actividades financieras y de seguros'],
            ['code' => 'L', 'name' => 'Actividades inmobiliarias'],
            ['code' => 'M', 'name' => 'Actividades profesionales, científicas y técnicas'],
            ['code' => 'N', 'name' => 'Actividades de servicios administrativos y de apoyo'],
            ['code' => 'O', 'name' => 'Administración pública y defensa; planes de seguridad social de afiliación obligatoria'],
            ['code' => 'P', 'name' => 'Enseñanza'],
            ['code' => 'Q', 'name' => 'Actividades de atención de la salud humana y de asistencia social'],
            ['code' => 'R', 'name' => 'Actividades artísticas, de entretenimiento y recreativas'],
            ['code' => 'S', 'name' => 'Otras actividades de servicios'],
            ['code' => 'T', 'name' => 'Actividades de los hogares como empleadores; actividades no diferenciadas de los hogares como productores de bienes y servicios para uso propio'],
            ['code' => 'U', 'name' => 'Actividades de organizaciones y órganos extraterritoriales'],
        ];

        $divisions = [
            ['section_code' => 'A', 'code' => '1', 'name' => 'Agricultura, ganadería, caza y servicios conexos'],
            ['section_code' => 'A', 'code' => '2', 'name' => 'Silvicultura y explotación de la madera'],
            ['section_code' => 'A', 'code' => '3', 'name' => 'Pesca y acuicultura'],
            ['section_code' => 'B', 'code' => '5', 'name' => 'Extracción de carbón'],
            ['section_code' => 'B', 'code' => '6', 'name' => 'Extracción de petróleo crudo y gas natural'],
            ['section_code' => 'B', 'code' => '7', 'name' => 'Extracción de minerales metalíferos'],
            ['section_code' => 'B', 'code' => '8', 'name' => 'Otras industrias extractivas'],
            ['section_code' => 'B', 'code' => '9', 'name' => 'Actividades de apoyo para la explotación de minas y canteras'],
            ['section_code' => 'C', 'code' => '10', 'name' => 'Elaboración de productos alimenticios'],
            ['section_code' => 'C', 'code' => '11', 'name' => 'Elaboración de bebidas'],
            ['section_code' => 'C', 'code' => '12', 'name' => 'Elaboración de productos de tabaco'],
            ['section_code' => 'C', 'code' => '13', 'name' => 'Fabricación de productos textiles'],
            ['section_code' => 'C', 'code' => '14', 'name' => 'Fabricación de prendas de vestir'],
            ['section_code' => 'C', 'code' => '15', 'name' => 'Fabricación de cuero y productos conexos'],
            ['section_code' => 'C', 'code' => '16', 'name' => 'Producción de madera y fabricación de productos de madera y corcho, excepto muebles; fabricación de artículos de paja y de materiales trenzables'],
            ['section_code' => 'C', 'code' => '17', 'name' => 'Fabricación de papel y de productos de papel'],
            ['section_code' => 'C', 'code' => '18', 'name' => 'Impresión y reproducción de grabaciones'],
            ['section_code' => 'C', 'code' => '19', 'name' => 'Fabricación de coque y de productos de la refinación del petróleo'],
            ['section_code' => 'C', 'code' => '20', 'name' => 'Fabricación de sustancias y productos químicos'],
            ['section_code' => 'C', 'code' => '21', 'name' => 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico'],
            ['section_code' => 'C', 'code' => '22', 'name' => 'Fabricación de productos de caucho y de plástico'],
            ['section_code' => 'C', 'code' => '23', 'name' => 'Fabricación de otros productos minerales no metálicos'],
            ['section_code' => 'C', 'code' => '24', 'name' => 'Fabricación de metales comunes'],
            ['section_code' => 'C', 'code' => '25', 'name' => 'Fabricación de productos elaborados de metal, excepto maquinaria y equipo'],
            ['section_code' => 'C', 'code' => '26', 'name' => 'Fabricación de productos informáticos, electrónicos y ópticos'],
            ['section_code' => 'C', 'code' => '27', 'name' => 'Fabricación de equipo eléctrico'],
            ['section_code' => 'C', 'code' => '28', 'name' => 'Fabricación de maquinaria y equipo n.c.p.'],
            ['section_code' => 'C', 'code' => '29', 'name' => 'Fabricación de vehículos automotores, remolques y semirremolques'],
            ['section_code' => 'C', 'code' => '30', 'name' => 'Fabricación de otros tipos de equipo de transporte'],
            ['section_code' => 'C', 'code' => '31', 'name' => 'Fabricación de muebles'],
            ['section_code' => 'C', 'code' => '32', 'name' => 'Otras industrias manufactureras'],
            ['section_code' => 'C', 'code' => '33', 'name' => 'Reparación e instalación de maquinaria y equipo'],
            ['section_code' => 'D', 'code' => '35', 'name' => 'Suministro de electricidad, gas, vapor y aire acondicionado'],
            ['section_code' => 'E', 'code' => '36', 'name' => 'Captación, tratamiento y distribución de agua'],
            ['section_code' => 'E', 'code' => '37', 'name' => 'Evacuación de aguas residuales'],
            ['section_code' => 'E', 'code' => '38', 'name' => 'Recolección, tratamiento y eliminación de desechos; recuperación de materiales'],
            ['section_code' => 'E', 'code' => '39', 'name' => 'Actividades de descontaminación y otros servicios de gestión de desechos'],
            ['section_code' => 'F', 'code' => '41', 'name' => 'Construcción de edificios'],
            ['section_code' => 'F', 'code' => '42', 'name' => 'Obras de ingeniería civil'],
            ['section_code' => 'F', 'code' => '43', 'name' => 'Actividades especializadas de construcción'],
            ['section_code' => 'G', 'code' => '45', 'name' => 'Comercio al por mayor y al por menor y reparación de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'code' => '46', 'name' => 'Comercio al por mayor, excepto de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'code' => '47', 'name' => 'Comercio al por menor, excepto de vehículos automotores y motocicletas'],
            ['section_code' => 'H', 'code' => '49', 'name' => 'Transporte terrestre y por tuberías'],
            ['section_code' => 'H', 'code' => '50', 'name' => 'Transporte acuático'],
            ['section_code' => 'H', 'code' => '51', 'name' => 'Transporte aéreo'],
            ['section_code' => 'H', 'code' => '52', 'name' => 'Almacenamiento y actividades de apoyo al transporte'],
            ['section_code' => 'H', 'code' => '53', 'name' => 'Actividades postales y de mensajería'],
            ['section_code' => 'I', 'code' => '55', 'name' => 'Actividades de alojamiento'],
            ['section_code' => 'I', 'code' => '56', 'name' => 'Actividades de servicio de comidas y bebidas'],
            ['section_code' => 'J', 'code' => '58', 'name' => 'Actividades de edición'],
            ['section_code' => 'J', 'code' => '59', 'name' => 'Actividades cinematográficas, de video y de producción de programas de televisión, grabación de sonido y edición de música'],
            ['section_code' => 'J', 'code' => '60', 'name' => 'Actividades de programación y transmisión'],
            ['section_code' => 'J', 'code' => '61', 'name' => 'Telecomunicaciones'],
            ['section_code' => 'J', 'code' => '62', 'name' => 'Programación informática, consultoría y actividades conexas'],
            ['section_code' => 'J', 'code' => '63', 'name' => 'Actividades de servicios de información'],
            ['section_code' => 'K', 'code' => '64', 'name' => 'Actividades de servicios financieros, excepto las de seguros y fondos de pensiones'],
            ['section_code' => 'K', 'code' => '65', 'name' => 'Seguros, reaseguros y fondos de pensiones, excepto los planes de seguridad social de afiliación obligatoria'],
            ['section_code' => 'K', 'code' => '66', 'name' => 'Actividades auxiliares de las actividades de servicios financieros y de seguros'],
            ['section_code' => 'L', 'code' => '68', 'name' => 'Actividades inmobiliarias'],
            ['section_code' => 'M', 'code' => '69', 'name' => 'Actividades jurídicas y de contabilidad'],
            ['section_code' => 'M', 'code' => '70', 'name' => 'Actividades de las sedes centrales; actividades de consultoría de gestión'],
            ['section_code' => 'M', 'code' => '71', 'name' => 'Servicios de arquitectura e ingeniería; ensayos y análisis técnicos'],
            ['section_code' => 'M', 'code' => '72', 'name' => 'Investigación y desarrollo científico'],
            ['section_code' => 'M', 'code' => '73', 'name' => 'Publicidad y estudios de mercado'],
            ['section_code' => 'M', 'code' => '74', 'name' => 'Otras actividades profesionales, científicas y técnicas'],
            ['section_code' => 'M', 'code' => '75', 'name' => 'Actividades veterinarias'],
            ['section_code' => 'N', 'code' => '77', 'name' => 'Actividades de alquiler y arrendamiento'],
            ['section_code' => 'N', 'code' => '78', 'name' => 'Actividades relacionadas con el empleo'],
            ['section_code' => 'N', 'code' => '79', 'name' => 'Actividades de agencias de viajes y operadores turísticos y servicios de reservas y actividades conexas'],
            ['section_code' => 'N', 'code' => '80', 'name' => 'Actividades de seguridad e investigación'],
            ['section_code' => 'N', 'code' => '81', 'name' => 'Actividades de servicios a edificios y paisajismo'],
            ['section_code' => 'N', 'code' => '82', 'name' => 'Actividades administrativas, de apoyo de oficina y otras actividades de apoyo a las empresas'],
            ['section_code' => 'O', 'code' => '84', 'name' => 'Administración pública y defensa; planes de seguridad social de afiliación obligatoria'],
            ['section_code' => 'P', 'code' => '85', 'name' => 'Enseñanza'],
            ['section_code' => 'Q', 'code' => '86', 'name' => 'Actividades de atención de la salud humana'],
            ['section_code' => 'Q', 'code' => '87', 'name' => 'Actividades de atención residencial'],
            ['section_code' => 'Q', 'code' => '88', 'name' => 'Actividades de asistencia social sin alojamiento'],
            ['section_code' => 'R', 'code' => '90', 'name' => 'Actividades creativas, artísticas y de entretenimiento'],
            ['section_code' => 'R', 'code' => '91', 'name' => 'Actividades de bibliotecas, archivos, museos y otras actividades culturales'],
            ['section_code' => 'R', 'code' => '92', 'name' => 'Actividades de juegos de azar y apuestas'],
            ['section_code' => 'R', 'code' => '93', 'name' => 'Actividades deportivas, de esparcimiento y recreativas'],
            ['section_code' => 'S', 'code' => '94', 'name' => 'Actividades de asociaciones'],
            ['section_code' => 'S', 'code' => '95', 'name' => 'Reparación de ordenadores y de efectos personales y enseres domésticos'],
            ['section_code' => 'S', 'code' => '96', 'name' => 'Otras actividades de servicios personales'],
            ['section_code' => 'T', 'code' => '97', 'name' => 'Actividades de los hogares como empleadores de personal doméstico'],
            ['section_code' => 'T', 'code' => '98', 'name' => 'Actividades no diferenciadas de los hogares como productores de bienes y servicios para uso propio'],
            ['section_code' => 'U', 'code' => '99', 'name' => 'Actividades de organizaciones y órganos extraterritoriales'],
        ];

        $groups = [
            ['section_code' => 'A', 'division_code' => '1', 'code' => '11', 'name' => 'Subgrupo 01-1 de agricultura, ganadería, caza y servicios conexos'],
            ['section_code' => 'A', 'division_code' => '1', 'code' => '12', 'name' => 'Subgrupo 01-2 de agricultura, ganadería, caza y servicios conexos'],
            ['section_code' => 'A', 'division_code' => '1', 'code' => '13', 'name' => 'Subgrupo 01-3 de agricultura, ganadería, caza y servicios conexos'],
            ['section_code' => 'A', 'division_code' => '2', 'code' => '21', 'name' => 'Subgrupo 02-1 de silvicultura y explotación de la madera'],
            ['section_code' => 'A', 'division_code' => '2', 'code' => '22', 'name' => 'Subgrupo 02-2 de silvicultura y explotación de la madera'],
            ['section_code' => 'A', 'division_code' => '2', 'code' => '23', 'name' => 'Subgrupo 02-3 de silvicultura y explotación de la madera'],
            ['section_code' => 'A', 'division_code' => '3', 'code' => '31', 'name' => 'Subgrupo 03-1 de pesca y acuicultura'],
            ['section_code' => 'A', 'division_code' => '3', 'code' => '32', 'name' => 'Subgrupo 03-2 de pesca y acuicultura'],
            ['section_code' => 'B', 'division_code' => '5', 'code' => '51', 'name' => 'Subgrupo 05-1 de extracción de carbón'],
            ['section_code' => 'B', 'division_code' => '5', 'code' => '52', 'name' => 'Subgrupo 05-2 de extracción de carbón'],
            ['section_code' => 'B', 'division_code' => '6', 'code' => '61', 'name' => 'Subgrupo 06-1 de extracción de petróleo crudo y gas natural'],
            ['section_code' => 'B', 'division_code' => '7', 'code' => '71', 'name' => 'Subgrupo 07-1 de extracción de minerales metalíferos'],
            ['section_code' => 'B', 'division_code' => '7', 'code' => '72', 'name' => 'Subgrupo 07-2 de extracción de minerales metalíferos'],
            ['section_code' => 'B', 'division_code' => '8', 'code' => '81', 'name' => 'Subgrupo 08-1 de otras industrias extractivas'],
            ['section_code' => 'B', 'division_code' => '8', 'code' => '89', 'name' => 'Subgrupo 08-9 de otras industrias extractivas'],
            ['section_code' => 'B', 'division_code' => '9', 'code' => '91', 'name' => 'Subgrupo 09-1 de actividades de apoyo para la explotación de minas y canteras'],
            ['section_code' => 'C', 'division_code' => '10', 'code' => '101', 'name' => 'Subgrupo 10-1 de elaboración de productos alimenticios'],
            ['section_code' => 'C', 'division_code' => '10', 'code' => '102', 'name' => 'Subgrupo 10-2 de elaboración de productos alimenticios'],
            ['section_code' => 'C', 'division_code' => '10', 'code' => '103', 'name' => 'Subgrupo 10-3 de elaboración de productos alimenticios'],
            ['section_code' => 'C', 'division_code' => '10', 'code' => '104', 'name' => 'Subgrupo 10-4 de elaboración de productos alimenticios'],
            ['section_code' => 'C', 'division_code' => '10', 'code' => '105', 'name' => 'Subgrupo 10-5 de elaboración de productos alimenticios'],
            ['section_code' => 'C', 'division_code' => '10', 'code' => '106', 'name' => 'Subgrupo 10-6 de elaboración de productos alimenticios'],
            ['section_code' => 'C', 'division_code' => '10', 'code' => '107', 'name' => 'Subgrupo 10-7 de elaboración de productos alimenticios'],
            ['section_code' => 'C', 'division_code' => '10', 'code' => '108', 'name' => 'Subgrupo 10-8 de elaboración de productos alimenticios'],
            ['section_code' => 'C', 'division_code' => '10', 'code' => '109', 'name' => 'Subgrupo 10-9 de elaboración de productos alimenticios'],
            ['section_code' => 'C', 'division_code' => '11', 'code' => '110', 'name' => 'Subgrupo 11-0 de elaboración de bebidas'],
            ['section_code' => 'C', 'division_code' => '12', 'code' => '120', 'name' => 'Subgrupo 12-0 de elaboración de productos de tabaco'],
            ['section_code' => 'C', 'division_code' => '13', 'code' => '131', 'name' => 'Subgrupo 13-1 de fabricación de productos textiles'],
            ['section_code' => 'C', 'division_code' => '13', 'code' => '139', 'name' => 'Subgrupo 13-9 de fabricación de productos textiles'],
            ['section_code' => 'C', 'division_code' => '14', 'code' => '141', 'name' => 'Subgrupo 14-1 de fabricación de prendas de vestir'],
            ['section_code' => 'C', 'division_code' => '14', 'code' => '142', 'name' => 'Subgrupo 14-2 de fabricación de prendas de vestir'],
            ['section_code' => 'C', 'division_code' => '14', 'code' => '143', 'name' => 'Subgrupo 14-3 de fabricación de prendas de vestir'],
            ['section_code' => 'C', 'division_code' => '15', 'code' => '151', 'name' => 'Subgrupo 15-1 de fabricación de cuero y productos conexos'],
            ['section_code' => 'C', 'division_code' => '15', 'code' => '152', 'name' => 'Subgrupo 15-2 de fabricación de cuero y productos conexos'],
            ['section_code' => 'C', 'division_code' => '16', 'code' => '161', 'name' => 'Subgrupo 16-1 de producción de madera y fabricación de productos de madera y corcho, excepto muebles; fabricación de artículos de paja y de materiales trenzables'],
            ['section_code' => 'C', 'division_code' => '16', 'code' => '162', 'name' => 'Subgrupo 16-2 de producción de madera y fabricación de productos de madera y corcho, excepto muebles; fabricación de artículos de paja y de materiales trenzables'],
            ['section_code' => 'C', 'division_code' => '17', 'code' => '170', 'name' => 'Subgrupo 17-0 de fabricación de papel y de productos de papel'],
            ['section_code' => 'C', 'division_code' => '18', 'code' => '181', 'name' => 'Subgrupo 18-1 de impresión y reproducción de grabaciones'],
            ['section_code' => 'C', 'division_code' => '18', 'code' => '182', 'name' => 'Subgrupo 18-2 de impresión y reproducción de grabaciones'],
            ['section_code' => 'C', 'division_code' => '19', 'code' => '191', 'name' => 'Subgrupo 19-1 de fabricación de coque y de productos de la refinación del petróleo'],
            ['section_code' => 'C', 'division_code' => '19', 'code' => '192', 'name' => 'Subgrupo 19-2 de fabricación de coque y de productos de la refinación del petróleo'],
            ['section_code' => 'C', 'division_code' => '20', 'code' => '201', 'name' => 'Subgrupo 20-1 de fabricación de sustancias y productos químicos'],
            ['section_code' => 'C', 'division_code' => '20', 'code' => '202', 'name' => 'Subgrupo 20-2 de fabricación de sustancias y productos químicos'],
            ['section_code' => 'C', 'division_code' => '20', 'code' => '203', 'name' => 'Subgrupo 20-3 de fabricación de sustancias y productos químicos'],
            ['section_code' => 'C', 'division_code' => '20', 'code' => '204', 'name' => 'Subgrupo 20-4 de fabricación de sustancias y productos químicos'],
            ['section_code' => 'C', 'division_code' => '20', 'code' => '205', 'name' => 'Subgrupo 20-5 de fabricación de sustancias y productos químicos'],
            ['section_code' => 'C', 'division_code' => '20', 'code' => '206', 'name' => 'Subgrupo 20-6 de fabricación de sustancias y productos químicos'],
            ['section_code' => 'C', 'division_code' => '20', 'code' => '210', 'name' => 'Subgrupo 21-0 de fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico'],
            ['section_code' => 'C', 'division_code' => '22', 'code' => '221', 'name' => 'Subgrupo 22-1 de fabricación de productos de caucho y de plástico'],
            ['section_code' => 'C', 'division_code' => '22', 'code' => '222', 'name' => 'Subgrupo 22-2 de fabricación de productos de caucho y de plástico'],
            ['section_code' => 'C', 'division_code' => '23', 'code' => '231', 'name' => 'Subgrupo 23-1 de fabricación de otros productos minerales no metálicos'],
            ['section_code' => 'C', 'division_code' => '23', 'code' => '239', 'name' => 'Subgrupo 23-9 de fabricación de otros productos minerales no metálicos'],
            ['section_code' => 'C', 'division_code' => '24', 'code' => '241', 'name' => 'Subgrupo 24-1 de fabricación de metales comunes'],
            ['section_code' => 'C', 'division_code' => '24', 'code' => '242', 'name' => 'Subgrupo 24-2 de fabricación de metales comunes'],
            ['section_code' => 'C', 'division_code' => '24', 'code' => '243', 'name' => 'Subgrupo 24-3 de fabricación de metales comunes'],
            ['section_code' => 'C', 'division_code' => '25', 'code' => '251', 'name' => 'Subgrupo 25-1 de fabricación de productos elaborados de metal, excepto maquinaria y equipo'],
            ['section_code' => 'C', 'division_code' => '25', 'code' => '252', 'name' => 'Subgrupo 25-2 de fabricación de productos elaborados de metal, excepto maquinaria y equipo'],
            ['section_code' => 'C', 'division_code' => '25', 'code' => '259', 'name' => 'Subgrupo 25-9 de fabricación de productos elaborados de metal, excepto maquinaria y equipo'],
            ['section_code' => 'C', 'division_code' => '26', 'code' => '261', 'name' => 'Subgrupo 26-1 de fabricación de productos informáticos, electrónicos y ópticos'],
            ['section_code' => 'C', 'division_code' => '26', 'code' => '262', 'name' => 'Subgrupo 26-2 de fabricación de productos informáticos, electrónicos y ópticos'],
            ['section_code' => 'C', 'division_code' => '26', 'code' => '263', 'name' => 'Subgrupo 26-3 de fabricación de productos informáticos, electrónicos y ópticos'],
            ['section_code' => 'C', 'division_code' => '26', 'code' => '264', 'name' => 'Subgrupo 26-4 de fabricación de productos informáticos, electrónicos y ópticos'],
            ['section_code' => 'C', 'division_code' => '26', 'code' => '265', 'name' => 'Subgrupo 26-5 de fabricación de productos informáticos, electrónicos y ópticos'],
            ['section_code' => 'C', 'division_code' => '26', 'code' => '266', 'name' => 'Subgrupo 26-6 de fabricación de productos informáticos, electrónicos y ópticos'],
            ['section_code' => 'C', 'division_code' => '26', 'code' => '267', 'name' => 'Subgrupo 26-7 de fabricación de productos informáticos, electrónicos y ópticos'],
            ['section_code' => 'C', 'division_code' => '26', 'code' => '268', 'name' => 'Subgrupo 26-8 de fabricación de productos informáticos, electrónicos y ópticos'],
            ['section_code' => 'C', 'division_code' => '27', 'code' => '271', 'name' => 'Subgrupo 27-1 de fabricación de equipo eléctrico'],
            ['section_code' => 'C', 'division_code' => '27', 'code' => '272', 'name' => 'Subgrupo 27-2 de fabricación de equipo eléctrico'],
            ['section_code' => 'C', 'division_code' => '27', 'code' => '273', 'name' => 'Subgrupo 27-3 de fabricación de equipo eléctrico'],
            ['section_code' => 'C', 'division_code' => '27', 'code' => '274', 'name' => 'Subgrupo 27-4 de fabricación de equipo eléctrico'],
            ['section_code' => 'C', 'division_code' => '27', 'code' => '275', 'name' => 'Subgrupo 27-5 de fabricación de equipo eléctrico'],
            ['section_code' => 'C', 'division_code' => '27', 'code' => '279', 'name' => 'Subgrupo 27-9 de fabricación de equipo eléctrico'],
            ['section_code' => 'C', 'division_code' => '28', 'code' => '281', 'name' => 'Subgrupo 28-1 de fabricación de maquinaria y equipo n.c.p.'],
            ['section_code' => 'C', 'division_code' => '28', 'code' => '282', 'name' => 'Subgrupo 28-2 de fabricación de maquinaria y equipo n.c.p.'],
            ['section_code' => 'C', 'division_code' => '28', 'code' => '283', 'name' => 'Subgrupo 28-3 de fabricación de maquinaria y equipo n.c.p.'],
            ['section_code' => 'C', 'division_code' => '28', 'code' => '289', 'name' => 'Subgrupo 28-9 de fabricación de maquinaria y equipo n.c.p.'],
            ['section_code' => 'C', 'division_code' => '29', 'code' => '291', 'name' => 'Subgrupo 29-1 de fabricación de vehículos automotores, remolques y semirremolques'],
            ['section_code' => 'C', 'division_code' => '29', 'code' => '292', 'name' => 'Subgrupo 29-2 de fabricación de vehículos automotores, remolques y semirremolques'],
            ['section_code' => 'C', 'division_code' => '29', 'code' => '293', 'name' => 'Subgrupo 29-3 de fabricación de vehículos automotores, remolques y semirremolques'],
            ['section_code' => 'C', 'division_code' => '30', 'code' => '301', 'name' => 'Subgrupo 30-1 de fabricación de otros tipos de equipo de transporte'],
            ['section_code' => 'C', 'division_code' => '30', 'code' => '302', 'name' => 'Subgrupo 30-2 de fabricación de otros tipos de equipo de transporte'],
            ['section_code' => 'C', 'division_code' => '30', 'code' => '303', 'name' => 'Subgrupo 30-3 de fabricación de otros tipos de equipo de transporte'],
            ['section_code' => 'C', 'division_code' => '30', 'code' => '304', 'name' => 'Subgrupo 30-4 de fabricación de otros tipos de equipo de transporte'],
            ['section_code' => 'C', 'division_code' => '30', 'code' => '309', 'name' => 'Subgrupo 30-9 de fabricación de otros tipos de equipo de transporte'],
            ['section_code' => 'C', 'division_code' => '31', 'code' => '310', 'name' => 'Subgrupo 31-0 de fabricación de muebles'],
            ['section_code' => 'C', 'division_code' => '32', 'code' => '321', 'name' => 'Subgrupo 32-1 de otras industrias manufactureras'],
            ['section_code' => 'C', 'division_code' => '32', 'code' => '322', 'name' => 'Subgrupo 32-2 de otras industrias manufactureras'],
            ['section_code' => 'C', 'division_code' => '32', 'code' => '323', 'name' => 'Subgrupo 32-3 de otras industrias manufactureras'],
            ['section_code' => 'C', 'division_code' => '32', 'code' => '324', 'name' => 'Subgrupo 32-4 de otras industrias manufactureras'],
            ['section_code' => 'C', 'division_code' => '32', 'code' => '325', 'name' => 'Subgrupo 32-5 de otras industrias manufactureras'],
            ['section_code' => 'C', 'division_code' => '32', 'code' => '329', 'name' => 'Subgrupo 32-9 de otras industrias manufactureras'],
            ['section_code' => 'C', 'division_code' => '33', 'code' => '331', 'name' => 'Subgrupo 33-1 de reparación e instalación de maquinaria y equipo'],
            ['section_code' => 'C', 'division_code' => '33', 'code' => '332', 'name' => 'Subgrupo 33-2 de reparación e instalación de maquinaria y equipo'],
            ['section_code' => 'D', 'division_code' => '35', 'code' => '351', 'name' => 'Subgrupo 35-1 de suministro de electricidad, gas, vapor y aire acondicionado'],
            ['section_code' => 'D', 'division_code' => '35', 'code' => '352', 'name' => 'Subgrupo 35-2 de suministro de electricidad, gas, vapor y aire acondicionado'],
            ['section_code' => 'D', 'division_code' => '35', 'code' => '353', 'name' => 'Subgrupo 35-3 de suministro de electricidad, gas, vapor y aire acondicionado'],
            ['section_code' => 'E', 'division_code' => '36', 'code' => '360', 'name' => 'Subgrupo 36-0 de captación, tratamiento y distribución de agua'],
            ['section_code' => 'E', 'division_code' => '37', 'code' => '370', 'name' => 'Subgrupo 37-0 de evacuación de aguas residuales'],
            ['section_code' => 'E', 'division_code' => '38', 'code' => '381', 'name' => 'Subgrupo 38-1 de recolección, tratamiento y eliminación de desechos; recuperación de materiales'],
            ['section_code' => 'E', 'division_code' => '38', 'code' => '382', 'name' => 'Subgrupo 38-2 de recolección, tratamiento y eliminación de desechos; recuperación de materiales'],
            ['section_code' => 'E', 'division_code' => '38', 'code' => '383', 'name' => 'Subgrupo 38-3 de recolección, tratamiento y eliminación de desechos; recuperación de materiales'],
            ['section_code' => 'E', 'division_code' => '39', 'code' => '390', 'name' => 'Subgrupo 39-0 de actividades de descontaminación y otros servicios de gestión de desechos'],
            ['section_code' => 'F', 'division_code' => '41', 'code' => '410', 'name' => 'Subgrupo 41-0 de construcción de edificios'],
            ['section_code' => 'F', 'division_code' => '42', 'code' => '421', 'name' => 'Subgrupo 42-1 de obras de ingeniería civil'],
            ['section_code' => 'F', 'division_code' => '42', 'code' => '422', 'name' => 'Subgrupo 42-2 de obras de ingeniería civil'],
            ['section_code' => 'F', 'division_code' => '42', 'code' => '429', 'name' => 'Subgrupo 42-9 de obras de ingeniería civil'],
            ['section_code' => 'F', 'division_code' => '43', 'code' => '431', 'name' => 'Subgrupo 43-1 de actividades especializadas de construcción'],
            ['section_code' => 'F', 'division_code' => '43', 'code' => '432', 'name' => 'Subgrupo 43-2 de actividades especializadas de construcción'],
            ['section_code' => 'F', 'division_code' => '43', 'code' => '433', 'name' => 'Subgrupo 43-3 de actividades especializadas de construcción'],
            ['section_code' => 'F', 'division_code' => '43', 'code' => '439', 'name' => 'Subgrupo 43-9 de actividades especializadas de construcción'],
            ['section_code' => 'G', 'division_code' => '45', 'code' => '451', 'name' => 'Subgrupo 45-1 de comercio al por mayor y al por menor y reparación de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'division_code' => '45', 'code' => '452', 'name' => 'Subgrupo 45-2 de comercio al por mayor y al por menor y reparación de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'division_code' => '45', 'code' => '453', 'name' => 'Subgrupo 45-3 de comercio al por mayor y al por menor y reparación de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'division_code' => '45', 'code' => '454', 'name' => 'Subgrupo 45-4 de comercio al por mayor y al por menor y reparación de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'division_code' => '46', 'code' => '461', 'name' => 'Subgrupo 46-1 de comercio al por mayor, excepto de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'division_code' => '46', 'code' => '462', 'name' => 'Subgrupo 46-2 de comercio al por mayor, excepto de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'division_code' => '46', 'code' => '463', 'name' => 'Subgrupo 46-3 de comercio al por mayor, excepto de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'division_code' => '46', 'code' => '464', 'name' => 'Subgrupo 46-4 de comercio al por mayor, excepto de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'division_code' => '46', 'code' => '465', 'name' => 'Subgrupo 46-5 de comercio al por mayor, excepto de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'division_code' => '46', 'code' => '466', 'name' => 'Subgrupo 46-6 de comercio al por mayor, excepto de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'division_code' => '46', 'code' => '467', 'name' => 'Subgrupo 46-7 de comercio al por mayor, excepto de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'division_code' => '46', 'code' => '469', 'name' => 'Subgrupo 46-9 de comercio al por mayor, excepto de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'division_code' => '47', 'code' => '471', 'name' => 'Subgrupo 47-1 de comercio al por menor, excepto de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'division_code' => '47', 'code' => '472', 'name' => 'Subgrupo 47-2 de comercio al por menor, excepto de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'division_code' => '47', 'code' => '473', 'name' => 'Subgrupo 47-3 de comercio al por menor, excepto de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'division_code' => '47', 'code' => '474', 'name' => 'Subgrupo 47-4 de comercio al por menor, excepto de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'division_code' => '47', 'code' => '475', 'name' => 'Subgrupo 47-5 de comercio al por menor, excepto de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'division_code' => '47', 'code' => '476', 'name' => 'Subgrupo 47-6 de comercio al por menor, excepto de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'division_code' => '47', 'code' => '477', 'name' => 'Subgrupo 47-7 de comercio al por menor, excepto de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'division_code' => '47', 'code' => '478', 'name' => 'Subgrupo 47-8 de comercio al por menor, excepto de vehículos automotores y motocicletas'],
            ['section_code' => 'G', 'division_code' => '47', 'code' => '479', 'name' => 'Subgrupo 47-9 de comercio al por menor, excepto de vehículos automotores y motocicletas'],
            ['section_code' => 'H', 'division_code' => '49', 'code' => '491', 'name' => 'Subgrupo 49-1 de transporte terrestre y por tuberías'],
            ['section_code' => 'H', 'division_code' => '49', 'code' => '492', 'name' => 'Subgrupo 49-2 de transporte terrestre y por tuberías'],
            ['section_code' => 'H', 'division_code' => '49', 'code' => '493', 'name' => 'Subgrupo 49-3 de transporte terrestre y por tuberías'],
            ['section_code' => 'H', 'division_code' => '50', 'code' => '501', 'name' => 'Subgrupo 50-1 de transporte acuático'],
            ['section_code' => 'H', 'division_code' => '50', 'code' => '502', 'name' => 'Subgrupo 50-2 de transporte acuático'],
            ['section_code' => 'H', 'division_code' => '51', 'code' => '511', 'name' => 'Subgrupo 51-1 de transporte aéreo'],
            ['section_code' => 'H', 'division_code' => '51', 'code' => '512', 'name' => 'Subgrupo 51-2 de transporte aéreo'],
            ['section_code' => 'H', 'division_code' => '52', 'code' => '521', 'name' => 'Subgrupo 52-1 de almacenamiento y actividades de apoyo al transporte'],
            ['section_code' => 'H', 'division_code' => '52', 'code' => '522', 'name' => 'Subgrupo 52-2 de almacenamiento y actividades de apoyo al transporte'],
            ['section_code' => 'H', 'division_code' => '53', 'code' => '531', 'name' => 'Subgrupo 53-1 de actividades postales y de mensajería'],
            ['section_code' => 'H', 'division_code' => '53', 'code' => '532', 'name' => 'Subgrupo 53-2 de actividades postales y de mensajería'],
            ['section_code' => 'I', 'division_code' => '55', 'code' => '551', 'name' => 'Subgrupo 55-1 de actividades de alojamiento'],
            ['section_code' => 'I', 'division_code' => '55', 'code' => '559', 'name' => 'Subgrupo 55-9 de actividades de alojamiento'],
            ['section_code' => 'I', 'division_code' => '56', 'code' => '561', 'name' => 'Subgrupo 56-1 de actividades de servicio de comidas y bebidas'],
            ['section_code' => 'I', 'division_code' => '56', 'code' => '562', 'name' => 'Subgrupo 56-2 de actividades de servicio de comidas y bebidas'],
            ['section_code' => 'I', 'division_code' => '56', 'code' => '563', 'name' => 'Subgrupo 56-3 de actividades de servicio de comidas y bebidas'],
            ['section_code' => 'J', 'division_code' => '58', 'code' => '581', 'name' => 'Subgrupo 58-1 de actividades de edición'],
            ['section_code' => 'J', 'division_code' => '58', 'code' => '582', 'name' => 'Subgrupo 58-2 de actividades de edición'],
            ['section_code' => 'J', 'division_code' => '59', 'code' => '591', 'name' => 'Subgrupo 59-1 de actividades cinematográficas, de video y de producción de programas de televisión, grabación de sonido y edición de música'],
            ['section_code' => 'J', 'division_code' => '59', 'code' => '592', 'name' => 'Subgrupo 59-2 de actividades cinematográficas, de video y de producción de programas de televisión, grabación de sonido y edición de música'],
            ['section_code' => 'J', 'division_code' => '60', 'code' => '601', 'name' => 'Subgrupo 60-1 de actividades de programación y transmisión'],
            ['section_code' => 'J', 'division_code' => '60', 'code' => '602', 'name' => 'Subgrupo 60-2 de actividades de programación y transmisión'],
            ['section_code' => 'J', 'division_code' => '61', 'code' => '611', 'name' => 'Subgrupo 61-1 de telecomunicaciones'],
            ['section_code' => 'J', 'division_code' => '61', 'code' => '612', 'name' => 'Subgrupo 61-2 de telecomunicaciones'],
            ['section_code' => 'J', 'division_code' => '61', 'code' => '613', 'name' => 'Subgrupo 61-3 de telecomunicaciones'],
            ['section_code' => 'J', 'division_code' => '61', 'code' => '619', 'name' => 'Subgrupo 61-9 de telecomunicaciones'],
            ['section_code' => 'J', 'division_code' => '62', 'code' => '620', 'name' => 'Subgrupo 62-0 de programación informática, consultoría y actividades conexas'],
            ['section_code' => 'J', 'division_code' => '63', 'code' => '631', 'name' => 'Subgrupo 63-1 de actividades de servicios de información'],
            ['section_code' => 'J', 'division_code' => '63', 'code' => '639', 'name' => 'Subgrupo 63-9 de actividades de servicios de información'],
            ['section_code' => 'K', 'division_code' => '64', 'code' => '641', 'name' => 'Subgrupo 64-1 de actividades de servicios financieros, excepto las de seguros y fondos de pensiones'],
            ['section_code' => 'K', 'division_code' => '64', 'code' => '642', 'name' => 'Subgrupo 64-2 de actividades de servicios financieros, excepto las de seguros y fondos de pensiones'],
            ['section_code' => 'K', 'division_code' => '64', 'code' => '643', 'name' => 'Subgrupo 64-3 de actividades de servicios financieros, excepto las de seguros y fondos de pensiones'],
            ['section_code' => 'K', 'division_code' => '64', 'code' => '649', 'name' => 'Subgrupo 64-9 de actividades de servicios financieros, excepto las de seguros y fondos de pensiones'],
            ['section_code' => 'K', 'division_code' => '65', 'code' => '651', 'name' => 'Subgrupo 65-1 de seguros, reaseguros y fondos de pensiones, excepto los planes de seguridad social de afiliación obligatoria'],
            ['section_code' => 'K', 'division_code' => '65', 'code' => '652', 'name' => 'Subgrupo 65-2 de seguros, reaseguros y fondos de pensiones, excepto los planes de seguridad social de afiliación obligatoria'],
            ['section_code' => 'K', 'division_code' => '65', 'code' => '653', 'name' => 'Subgrupo 65-3 de seguros, reaseguros y fondos de pensiones, excepto los planes de seguridad social de afiliación obligatoria'],
            ['section_code' => 'K', 'division_code' => '66', 'code' => '661', 'name' => 'Subgrupo 66-1 de actividades auxiliares de las actividades de servicios financieros y de seguros'],
            ['section_code' => 'K', 'division_code' => '66', 'code' => '662', 'name' => 'Subgrupo 66-2 de actividades auxiliares de las actividades de servicios financieros y de seguros'],
            ['section_code' => 'K', 'division_code' => '66', 'code' => '663', 'name' => 'Subgrupo 66-3 de actividades auxiliares de las actividades de servicios financieros y de seguros'],
            ['section_code' => 'L', 'division_code' => '68', 'code' => '681', 'name' => 'Subgrupo 68-1 de actividades inmobiliarias'],
            ['section_code' => 'L', 'division_code' => '68', 'code' => '682', 'name' => 'Subgrupo 68-2 de actividades inmobiliarias'],
            ['section_code' => 'M', 'division_code' => '69', 'code' => '691', 'name' => 'Subgrupo 69-1 de actividades jurídicas y de contabilidad'],
            ['section_code' => 'M', 'division_code' => '69', 'code' => '692', 'name' => 'Subgrupo 69-2 de actividades jurídicas y de contabilidad'],
            ['section_code' => 'M', 'division_code' => '70', 'code' => '701', 'name' => 'Subgrupo 70-1 de actividades de las sedes centrales; actividades de consultoría de gestión'],
            ['section_code' => 'M', 'division_code' => '70', 'code' => '702', 'name' => 'Subgrupo 70-2 de actividades de las sedes centrales; actividades de consultoría de gestión'],
            ['section_code' => 'M', 'division_code' => '71', 'code' => '711', 'name' => 'Subgrupo 71-1 de servicios de arquitectura e ingeniería; ensayos y análisis técnicos'],
            ['section_code' => 'M', 'division_code' => '71', 'code' => '712', 'name' => 'Subgrupo 71-2 de servicios de arquitectura e ingeniería; ensayos y análisis técnicos'],
            ['section_code' => 'M', 'division_code' => '72', 'code' => '721', 'name' => 'Subgrupo 72-1 de investigación y desarrollo científico'],
            ['section_code' => 'M', 'division_code' => '72', 'code' => '722', 'name' => 'Subgrupo 72-2 de investigación y desarrollo científico'],
            ['section_code' => 'M', 'division_code' => '73', 'code' => '731', 'name' => 'Subgrupo 73-1 de publicidad y estudios de mercado'],
            ['section_code' => 'M', 'division_code' => '73', 'code' => '732', 'name' => 'Subgrupo 73-2 de publicidad y estudios de mercado'],
            ['section_code' => 'M', 'division_code' => '74', 'code' => '741', 'name' => 'Subgrupo 74-1 de otras actividades profesionales, científicas y técnicas'],
            ['section_code' => 'M', 'division_code' => '74', 'code' => '742', 'name' => 'Subgrupo 74-2 de otras actividades profesionales, científicas y técnicas'],
            ['section_code' => 'M', 'division_code' => '74', 'code' => '749', 'name' => 'Subgrupo 74-9 de otras actividades profesionales, científicas y técnicas'],
            ['section_code' => 'M', 'division_code' => '75', 'code' => '750', 'name' => 'Subgrupo 75-0 de actividades veterinarias'],
            ['section_code' => 'N', 'division_code' => '77', 'code' => '771', 'name' => 'Subgrupo 77-1 de actividades de alquiler y arrendamiento'],
            ['section_code' => 'N', 'division_code' => '77', 'code' => '772', 'name' => 'Subgrupo 77-2 de actividades de alquiler y arrendamiento'],
            ['section_code' => 'N', 'division_code' => '77', 'code' => '773', 'name' => 'Subgrupo 77-3 de actividades de alquiler y arrendamiento'],
            ['section_code' => 'N', 'division_code' => '77', 'code' => '774', 'name' => 'Subgrupo 77-4 de actividades de alquiler y arrendamiento'],
            ['section_code' => 'N', 'division_code' => '77', 'code' => '775', 'name' => 'Subgrupo 77-5 de actividades de alquiler y arrendamiento'],
            ['section_code' => 'N', 'division_code' => '77', 'code' => '779', 'name' => 'Subgrupo 77-9 de actividades de alquiler y arrendamiento'],
            ['section_code' => 'N', 'division_code' => '78', 'code' => '781', 'name' => 'Subgrupo 78-1 de actividades relacionadas con el empleo'],
            ['section_code' => 'N', 'division_code' => '78', 'code' => '782', 'name' => 'Subgrupo 78-2 de actividades relacionadas con el empleo'],
            ['section_code' => 'N', 'division_code' => '78', 'code' => '783', 'name' => 'Subgrupo 78-3 de actividades relacionadas con el empleo'],
            ['section_code' => 'N', 'division_code' => '79', 'code' => '791', 'name' => 'Subgrupo 79-1 de actividades de agencias de viajes y operadores turísticos y servicios de reservas y actividades conexas'],
            ['section_code' => 'N', 'division_code' => '79', 'code' => '799', 'name' => 'Subgrupo 79-9 de actividades de agencias de viajes y operadores turísticos y servicios de reservas y actividades conexas'],
            ['section_code' => 'N', 'division_code' => '80', 'code' => '801', 'name' => 'Subgrupo 80-1 de actividades de seguridad e investigación'],
            ['section_code' => 'N', 'division_code' => '80', 'code' => '802', 'name' => 'Subgrupo 80-2 de actividades de seguridad e investigación'],
            ['section_code' => 'N', 'division_code' => '80', 'code' => '803', 'name' => 'Subgrupo 80-3 de actividades de seguridad e investigación'],
            ['section_code' => 'N', 'division_code' => '81', 'code' => '811', 'name' => 'Subgrupo 81-1 de actividades de servicios a edificios y paisajismo'],
            ['section_code' => 'N', 'division_code' => '81', 'code' => '812', 'name' => 'Subgrupo 81-2 de actividades de servicios a edificios y paisajismo'],
            ['section_code' => 'N', 'division_code' => '81', 'code' => '813', 'name' => 'Subgrupo 81-3 de actividades de servicios a edificios y paisajismo'],
            ['section_code' => 'N', 'division_code' => '82', 'code' => '821', 'name' => 'Subgrupo 82-1 de actividades administrativas, de apoyo de oficina y otras actividades de apoyo a las empresas'],
            ['section_code' => 'N', 'division_code' => '82', 'code' => '822', 'name' => 'Subgrupo 82-2 de actividades administrativas, de apoyo de oficina y otras actividades de apoyo a las empresas'],
            ['section_code' => 'N', 'division_code' => '82', 'code' => '823', 'name' => 'Subgrupo 82-3 de actividades administrativas, de apoyo de oficina y otras actividades de apoyo a las empresas'],
            ['section_code' => 'N', 'division_code' => '82', 'code' => '829', 'name' => 'Subgrupo 82-9 de actividades administrativas, de apoyo de oficina y otras actividades de apoyo a las empresas'],
            ['section_code' => 'O', 'division_code' => '84', 'code' => '841', 'name' => 'Subgrupo 84-1 de administración pública y defensa; planes de seguridad social de afiliación obligatoria'],
            ['section_code' => 'O', 'division_code' => '84', 'code' => '842', 'name' => 'Subgrupo 84-2 de administración pública y defensa; planes de seguridad social de afiliación obligatoria'],
            ['section_code' => 'O', 'division_code' => '84', 'code' => '843', 'name' => 'Subgrupo 84-3 de administración pública y defensa; planes de seguridad social de afiliación obligatoria'],
            ['section_code' => 'P', 'division_code' => '85', 'code' => '851', 'name' => 'Subgrupo 85-1 de enseñanza'],
            ['section_code' => 'P', 'division_code' => '85', 'code' => '852', 'name' => 'Subgrupo 85-2 de enseñanza'],
            ['section_code' => 'P', 'division_code' => '85', 'code' => '853', 'name' => 'Subgrupo 85-3 de enseñanza'],
            ['section_code' => 'P', 'division_code' => '85', 'code' => '854', 'name' => 'Subgrupo 85-4 de enseñanza'],
            ['section_code' => 'P', 'division_code' => '85', 'code' => '855', 'name' => 'Subgrupo 85-5 de enseñanza'],
            ['section_code' => 'P', 'division_code' => '85', 'code' => '856', 'name' => 'Subgrupo 85-6 de enseñanza'],
            ['section_code' => 'Q', 'division_code' => '86', 'code' => '861', 'name' => 'Subgrupo 86-1 de actividades de atención de la salud humana'],
            ['section_code' => 'Q', 'division_code' => '86', 'code' => '862', 'name' => 'Subgrupo 86-2 de actividades de atención de la salud humana'],
            ['section_code' => 'Q', 'division_code' => '86', 'code' => '869', 'name' => 'Subgrupo 86-9 de actividades de atención de la salud humana'],
            ['section_code' => 'Q', 'division_code' => '87', 'code' => '871', 'name' => 'Subgrupo 87-1 de actividades de atención residencial'],
            ['section_code' => 'Q', 'division_code' => '87', 'code' => '872', 'name' => 'Subgrupo 87-2 de actividades de atención residencial'],
            ['section_code' => 'Q', 'division_code' => '87', 'code' => '873', 'name' => 'Subgrupo 87-3 de actividades de atención residencial'],
            ['section_code' => 'Q', 'division_code' => '87', 'code' => '879', 'name' => 'Subgrupo 87-9 de actividades de atención residencial'],
            ['section_code' => 'Q', 'division_code' => '88', 'code' => '881', 'name' => 'Subgrupo 88-1 de actividades de asistencia social sin alojamiento'],
            ['section_code' => 'Q', 'division_code' => '88', 'code' => '889', 'name' => 'Subgrupo 88-9 de actividades de asistencia social sin alojamiento'],
            ['section_code' => 'R', 'division_code' => '90', 'code' => '900', 'name' => 'Subgrupo 90-0 de actividades creativas, artísticas y de entretenimiento'],
            ['section_code' => 'R', 'division_code' => '91', 'code' => '910', 'name' => 'Subgrupo 91-0 de actividades de bibliotecas, archivos, museos y otras actividades culturales'],
            ['section_code' => 'R', 'division_code' => '92', 'code' => '920', 'name' => 'Subgrupo 92-0 de actividades de juegos de azar y apuestas'],
            ['section_code' => 'R', 'division_code' => '93', 'code' => '931', 'name' => 'Subgrupo 93-1 de actividades deportivas, de esparcimiento y recreativas'],
            ['section_code' => 'R', 'division_code' => '93', 'code' => '932', 'name' => 'Subgrupo 93-2 de actividades deportivas, de esparcimiento y recreativas'],
            ['section_code' => 'S', 'division_code' => '94', 'code' => '941', 'name' => 'Subgrupo 94-1 de actividades de asociaciones'],
            ['section_code' => 'S', 'division_code' => '94', 'code' => '942', 'name' => 'Subgrupo 94-2 de actividades de asociaciones'],
            ['section_code' => 'S', 'division_code' => '94', 'code' => '949', 'name' => 'Subgrupo 94-9 de actividades de asociaciones'],
            ['section_code' => 'S', 'division_code' => '95', 'code' => '951', 'name' => 'Subgrupo 95-1 de reparación de ordenadores y de efectos personales y enseres domésticos'],
            ['section_code' => 'S', 'division_code' => '95', 'code' => '952', 'name' => 'Subgrupo 95-2 de reparación de ordenadores y de efectos personales y enseres domésticos'],
            ['section_code' => 'S', 'division_code' => '96', 'code' => '961', 'name' => 'Subgrupo 96-1 de otras actividades de servicios personales'],
            ['section_code' => 'S', 'division_code' => '96', 'code' => '962', 'name' => 'Subgrupo 96-2 de otras actividades de servicios personales'],
            ['section_code' => 'S', 'division_code' => '96', 'code' => '963', 'name' => 'Subgrupo 96-3 de otras actividades de servicios personales'],
            ['section_code' => 'S', 'division_code' => '96', 'code' => '969', 'name' => 'Subgrupo 96-9 de otras actividades de servicios personales'],
            ['section_code' => 'T', 'division_code' => '97', 'code' => '970', 'name' => 'Subgrupo 97-0 de actividades de los hogares como empleadores de personal doméstico'],
            ['section_code' => 'T', 'division_code' => '98', 'code' => '981', 'name' => 'Subgrupo 98-1 de actividades no diferenciadas de los hogares como productores de bienes y servicios para uso propio'],
            ['section_code' => 'T', 'division_code' => '98', 'code' => '982', 'name' => 'Subgrupo 98-2 de actividades no diferenciadas de los hogares como productores de bienes y servicios para uso propio'],
            ['section_code' => 'U', 'division_code' => '99', 'code' => '990', 'name' => 'Subgrupo 99-0 de actividades de organizaciones y órganos extraterritoriales'],
        ];

        // 1) Secciones (level = SECTION)
        $sectionMap = [];
        foreach ($sections as $item) {
            $record = EconomicSector::updateOrCreate(
                [
                    'name' => $item['name'],
                    'parent_id' => null,
                ],
                [
                    'level' => EconomicSectorLevel::SECTION->value,
                ]
            );

            $sectionMap[$item['code']] = $record->id;
        }

        // 2) Divisiones (level = DIVISION)
        $divisionMap = [];
        foreach ($divisions as $item) {
            $parentId = $sectionMap[$item['section_code']] ?? null;

            $record = EconomicSector::updateOrCreate(
                [
                    'name' => $item['name'],
                    'parent_id' => $parentId,
                ],
                [
                    'level' => EconomicSectorLevel::DIVISION->value,
                ]
            );

            // clave compuesta: "A-1", "C-10", etc.
            $divisionMap[$item['section_code'] . '-' . $item['code']] = $record->id;
        }

        // 3) Grupos (level = GROUP)
        foreach ($groups as $item) {
            $parentId = $divisionMap[$item['section_code'] . '-' . $item['division_code']] ?? null;

            EconomicSector::updateOrCreate(
                [
                    'name' => $item['name'],
                    'parent_id' => $parentId,
                ],
                [
                    'level' => EconomicSectorLevel::GROUP->value,
                ]
            );
        }
    }
}
