export const resourceType = {
    academic: "Académico/investigador",
    academic_body: "Cuerpo académico",
    academic_offering: "Oferta educativa",
    institution_certification: "Certificación",
    conference: "Conferencia",
    capability: "Capacidad tecnológica",
    company: "Empresa",
    equipment: "Infraestructura tecnológica",
    facility: "Instalación especializada",
    government_agency: "Dependencia gubernamental",
    higher_education: "Institución de educación superior",
    research_center: "Centro de investigación",
    job_offer: "Oferta laboral",
    non_profit: "Organización no gubernamental",
    requirement: "Necesidad tecnológica",
    research_line: "Línea de investigación",
    technology_service: "Servicio tecnológico",
};

export const resourceColor = {
    academic: "forest",
    academic_body: "forest",
    academic_offering: "forest",
    capability: "wine",
    institution_certification: "wine",
    company: "wine",
    conference: "wine",
    equipment: "wine",
    facility: "forest",
    government_agency: "wine",
    higher_education: "wine",
    research_center: "wine",
    job_offer: "forest",
    non_profit: "wine",
    requirement: "wine",
    research_line: "wine",
    technology_service: "wine",
};
