import {
    mdiChartBar,
    mdiShapeOutline,
    mdiBookOpenVariant,
    mdiFormatListBulleted,
    mdiShape,
    mdiSchoolOutline,
    mdiBrain,
    mdiDomain,
    mdiCubeOutline,
    mdiStarFourPoints,
    mdiNewspaperVariantOutline,
    mdiCertificateOutline,
    mdiCastEducation,
    mdiHandshake,
    mdiAccountSchoolOutline,
    mdiBookEducationOutline,
    mdiAccountCash,
    mdiAccountFileText,
    mdiCertificate,
} from "@mdi/js";

export default [
    {
        label: "Catálogos",
        permission: "menu.catalog",
        icon: mdiShape,
        menu: [
            {
                label: "OCDE",
                route: "oecdSector.index",
                icon: mdiSchoolOutline,
                permission: "oecdSector.index",
            },
            {
                label: "TLR",
                route: "technologyLevels.index",
                icon: mdiShapeOutline,
                permission: "technologyLevels.index",
            },
            {
                label: "Actividades",
                route: "activities.index",
                icon: mdiShapeOutline,
                permission: "activities.index",
            },
            {
                label: "Sector Económico",
                route: "economicSectors.index",
                icon: mdiChartBar,
                permission: "economicSectors.index",
            },
            {
                label: "Área de Conocimiento",
                route: "knowledgeAreas.index",
                icon: mdiBrain,
                permission: "knowledgeAreas.index",
            },
            {
                label: "Tipos de Institución",
                route: "institutionTypes.index",
                icon: mdiDomain,
                permission: "institutionTypes.index",
            },
            {
                label: "Tipos de Recurso",
                route: "resourceTypes.index",
                icon: mdiCubeOutline,
                permission: "resourceTypes.index",
            },
            {
                label: "Propiedades Intelectuales",
                route: "intellectualProperties.index",
                icon: mdiBookOpenVariant,
                permission: "intellectualProperties.index",
            },
            {
                label: "Tipos de Instalación",
                route: "facilityTypes.index",
                icon: mdiDomain,
                permission: "facilityTypes.index",
            },
            {
                label: "Tipos de infrastructura tecnológica",
                route: "equipmentTypes.index",
                icon: mdiDomain,
                permission: "equipmentTypes.index",
            },
            {
                label: "Sector social",
                route: "socialSectors.index",
                icon: mdiHandshake,
                permission: "socialSectors.index",
            },
            {
                label: "Áreas SNII",
                route: "researchAreas.index",
                icon: mdiBookEducationOutline,
                permission: "researchAreas.index",
            },/*
            {
                label: "ISIC",
                route: "productiveEconomicSectors.index",
                icon: mdiAccountCash,
                permission: "productiveEconomicSectors.index",
            },*/
            {
                label: "Nivel Educativo",
                route: "educationalLevels.index",
                icon: mdiAccountSchoolOutline,
                permission: "educationalLevels.index",
            },
            {
                label: "Modalidad educativa",
                route: "educationalModalities.index",
                icon: mdiCastEducation,
                permission: "educationalModalities.index",
            },
            {
                label: "Acreditación COPAES",
                route: "copaesAccreditations.index",
                icon: mdiCertificateOutline,
                permission: "copaesAccreditations.index",
            },
            {
                label: "Acreditación CIEES",
                route: "cieesAccreditations.index",
                icon: mdiCertificateOutline,
                permission: "cieesAccreditations.index",
            },
            {
                label: "Acreditación FIMPES",
                route: "fimpesAccreditations.index",
                icon: mdiCertificateOutline,
                permission: "fimpesAccreditations.index",
            },
            {
                label: "Categoría noticia",
                route: "newsCategories.index",
                icon: mdiNewspaperVariantOutline,
                permission: "newsCategories.index",
            },
            {
                label: "Categorías de servicio tecnológico",
                route: "technologyServiceCategories.index",
                icon: mdiFormatListBulleted,
                permission: "technologyServiceCategories.index",
            },
            {
                label: "Tipos de servicio tecnológico",
                route: "technologyServiceTypes.index",
                icon: mdiStarFourPoints,
                permission: "technologyServiceTypes.index",
            },
            {
                label: "Categorías de evaluación",
                route: "matchEvaluationCategories.index",
                icon: mdiShapeOutline,
                permission: "matchEvaluationCategories.index",
            },
            {
                label: "Métricas de impacto",
                route: "impactMetrics.index",
                icon: mdiAccountFileText,
                permission: "impactMetrics.index",
            },
            {
                label: "Sectores gubernamentales",
                route: "governmentSectors.index",
                icon: mdiDomain,
                permission: "governmentSectors.index",
            },
            {
                label: "Tipos de certificación",
                route: "certificationTypes.index",
                icon: mdiCertificate,
                permission: "certificationTypes.index",
            },
        ],
    },
]